### PR TITLE
Update to GNOME 45

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
@hfiguiere Any idea?

**Comment by hfiguiere** [comment]
line 3264 in the log

In file included from /run/build/webkit2gtk-4.0/Source/ThirdParty/ANGLE/src/compiler/translator/Compiler.h:17,
                 from /run/build/webkit2gtk-4.0/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorESSL.h:10,
                 from /run/build/webkit2gtk-4.0/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorESSL.cpp:7:
/run/build/webkit2gtk-4.0/Source/ThirdParty/ANGLE/include/GLSLANG/ShaderVars.h:19:26: error: ‘uint64_t’ does not name a type
   19 | using ShCompileOptions = uint64_t;
      |                          ^~~~~~~~
/run/build/webkit2gtk-4.0/Source/ThirdParty/ANGLE/include/GLSLANG/ShaderVars.h:17:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   16 | #include <vector>
  +++ |+#include <cstdint>
   17 | 

start with that.

**Comment by AsciiWolf** [comment]
@cho2 We should try updating the webkit2gtk-4.0 module.

**Comment by hfiguiere** [comment]
> @cho2 We should try updating the webkit2gtk-4.0 module.

to what? wxWdiget doesn't build with the 4.1 that is in the runtime.

**Comment by hfiguiere** [comment]
maybe to this one https://webkitgtk.org/releases/webkitgtk-2.42.4.tar.xz
